#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries. Simply type the
# menu entries you want to add after this comment. Be careful not to change
# the 'exec tail' line above.

menuentry "PrimeOS" --class android {
    insmod part_gpt
    insmod ext4
    search --no-floppy --fs-uuid --set=root a808188f-7c07-40b0-bdbc-0ceed9c0bb82

    linux /android-2.1.3/kernel quiet root=/dev/ram0 androidboot.selinux=permissive buildvariant=userdebug SRC=/android-2.1.3
    initrd /android-2.1.3/initrd.img
}
